import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";
import nasaLogo from "../public/images/nasa-logo.png";
import PhotoCard from "../components/photoCard";

export default function Home({ nasaPhoto }) {
  console.log({ nasaPhoto });
  return (
    <div className={styles.container}>
      <Head>
        <title>NextJS NASA APOD</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
          <Image
            className="nasa-logo"
            src={nasaLogo}
            alt="Nasa Logo"
            height={144}
            width={280}
          />
          <h1 className={styles.title}>Astronomy Photo of the Day</h1>
    
          <PhotoCard nasaPhoto={nasaPhoto} />
        
        <div className={styles.grid}>
          <a
            href="https://apod.nasa.gov/apod/image/2204/M24_APOD_GabrielRodriguesSantosAPOD.jpg"
            target="_blank"
            rel="noreferrer"
            className={styles.card}
          >
            <h2>HD Resolution</h2>
          </a>

          <a
            href="https://www.nasa.gov/multimedia/imagegallery/index.html"
            target="_blank"
            rel="noreferrer"
            className={styles.card}
          >
            <h2>NASA Image Gallery</h2>
          </a>

          <a
            href="https://www.nasa.gov/"
            target="_blank"
            rel="noreferrer"
            className={styles.card}
          >
            <h2>NASA Website</h2>
          </a>

          <a
            href="https://www.nasa.gov/nasa-at-home-be-a-scientist"
            target="_blank"
            rel="noreferrer"
            className={styles.card}
          >
            <h2>Be a Scientist!</h2>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}

export async function getServerSideProps() {
  const res = await fetch(
    "https://api.nasa.gov/planetary/apod?api_key=ZpebsFfzozubPgYXkFi5TckqXCf0JsEoofTxqzoZ"
  );
  const nasaPhoto = await res.json();
  return {
    props: { nasaPhoto },
  };
}
