import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";
import PhotoCard from "../components/photoCard";

export default function Home({ nasaPhoto }) {
  console.log({ nasaPhoto });
  return (
    <div className={styles.container}>
      <Head>
        <title>NextJS NASA APOD</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Image
          className="nasa-logo"
          src="/images/nasa-logo.png"
          alt="Nasa Logo"
          height={144}
          width={280}
        />
        <h1 className={styles.title}>Astronomy Photo of the Day</h1>

        <PhotoCard nasaPhoto={nasaPhoto} />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}

export async function getServerSideProps() {
  const res = await fetch(
    "https://api.nasa.gov/planetary/apod?api_key=ZpebsFfzozubPgYXkFi5TckqXCf0JsEoofTxqzoZ"
  );
  const nasaPhoto = await res.json();
  return {
    props: { nasaPhoto },
  };
}
